name: fono_terapia
description: Um aplicativo para pacientes treinar a fala.

publish_to: 'none'

version: 0.0.1+6

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  path: ^1.8.3
  sqflite: ^2.3.2
  audioplayers: ^6.0.0
  async: ^2.11.0
  characters: ^1.3.0
  diacritic: ^0.1.5

  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  provider: ^6.1.2
  cloud_firestore: ^5.2.1
  in_app_purchase: ^3.2.0

flutter_launcher_icons:
  image_path: "assets/app_assets/app_icon.png"
  ios: false
  android: "launcher_icon"
  adaptative_icon_background: "#FFFFFF"
  adaptative_icon_foreground: "assets/app_assets/app_icon.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/app_assets/
  - assets/app_assets/sub_categories/
  - assets/db_images/
  - assets/db_audios/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf